# Generate Paper Assessment Annotations

This notebook splits the annotated dataset into a dev set (250 samples) and test set (250 samples)

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df_annotations = pd.read_csv("../data/02_paper_assessment/raw_annotations_paper_assessment.csv")
df_full_text = pd.read_parquet("../data/01_full_text/references_with_full_text.parquet.br")

In [3]:
# Add full text by joining on PMID

df_annotations = df_annotations.merge(
    df_full_text[["PMID", "full_text"]],
    on="PMID",
    how="left"
)

In [4]:
# Add gt_ prefix to annotated columns

df_annotations = df_annotations.rename(
    columns={col: f"gt_{col}" for col in ["in_scope", "has_repo", "repo_url"]}
)

In [5]:
# reorder columns

df_annotations = df_annotations[["PMID", "full_text", "gt_in_scope", "gt_has_repo", "gt_repo_url"]]

In [7]:
df_annotations.to_csv("../data/02_paper_assessment/gt_paper_assessment.csv")

In [3]:
# Randomly split into two halves
dev, test = train_test_split(df_annotations, test_size=0.5, random_state=42)

# Reset index for both halves
dev = dev.reset_index(drop=True)
test = test.reset_index(drop=True)

In [9]:
df_annotations

,PMCID,in_scope,has_repo,repo_url,PMID,full_text
0,PMC10004854,Yes,No,NaN,36904233,==== Front\nNutrients\nNutrients\nnutrients\nN...
1,PMC10013725,Yes,No,NaN,36911893,==== Front\nPerm J\ntpj\ntpj\nThe Permanente J...
2,PMC10028662,Yes,No,NaN,36935582,==== Front\nJ Int Med Res\nJ Int Med Res\nIMR\...
3,PMC10077108,Yes,Yes,https://github.com/mgregorich/BEAt-DKD_PredeGFR,37017968,==== Front\nJAMA Netw Open\nJAMA Netw Open\nJA...
4,PMC10090728,Yes,No,NaN,36384245,==== Front\nClin Exp Emerg Med\nClin Exp Emerg...
...,...,...,...,...,...,...
495,PMC9971890,No,NaN,NaN,36866292,==== Front\nArthrosc Sports Med Rehabil\nArthr...
496,PMC9972034,Yes,No,NaN,36128836,==== Front\nCancer Med\nCancer Med\n10.1002/(I...
497,PMC9978473,Yes,Yes,https://github.com/putzfn/HNLNL_autosegmentati...,36874135,==== Front\nFront Oncol\nFront Oncol\nFront. O...
498,PMC9978756,Yes,No,NaN,36936595,==== Front\nBMJ Med\nBMJ Med\nbmjmed\nbmjmed\n...
499,PMC9978899,Yes,No,NaN,36596755,==== Front\nClin Respir J\nClin Respir J\n10.1...

In [7]:
df_annotations

,PMCID,in_scope,has_repo,repo_url
0,PMC10004854,Yes,No,NaN
1,PMC10013725,Yes,No,NaN
2,PMC10028662,Yes,No,NaN
3,PMC10077108,Yes,Yes,https://github.com/mgregorich/BEAt-DKD_PredeGFR
4,PMC10090728,Yes,No,NaN
...,...,...,...,...
495,PMC9971890,No,NaN,NaN
496,PMC9972034,Yes,No,NaN
497,PMC9978473,Yes,Yes,https://github.com/putzfn/HNLNL_autosegmentati...
498,PMC9978756,Yes,No,NaN
499,PMC9978899,Yes,No,NaN

In [6]:
df_full_text

,PMID,Title,Authors,Citation,First Author,Journal/Book,Publication Year,Create Date,PMCID,NIHMS ID,DOI,full_text
0,35799302,Development and validation of a multivariable ...,"Iachkine J, Buetti N, de Grooth HJ, Briant AR,...",Crit Care. 2022 Jul 7;26(1):205. doi: 10.1186/...,Iachkine J,Crit Care,2022,2022/07/07,PMC9261073,None,10.1186/s13054-022-04078-x,==== Front\nCrit Care\nCritical Care\n1364-853...
1,40151494,Development and validation of a risk-predictio...,"Qian J, Ruan C, Cai Y, Yi W, Liu J, Xu R.",Ther Adv Drug Saf. 2025 Mar 22;16:204209862513...,Qian J,Ther Adv Drug Saf,2025,2025/03/28,PMC11946284,None,10.1177/20420986251328687,==== Front\nTher Adv Drug Saf\nTher Adv Drug S...
2,36383295,28-day sepsis mortality prediction model from ...,"Xie Y, Zhuang D, Chen H, Zou S, Chen W, Chen Y.",Eur J Clin Microbiol Infect Dis. 2023 Jan;42(1...,Xie Y,Eur J Clin Microbiol Infect Dis,2023,2022/11/16,PMC9816294,None,10.1007/s10096-022-04517-1,==== Front\nEur J Clin Microbiol Infect Dis\nE...
3,33746422,Development of a multivariable prediction mode...,"Andersen JD, Hangaard S, Buus AAØ, Laursen M, ...",J Orthop. 2021 Mar 11;24:216-221. doi: 10.1016...,Andersen JD,J Orthop,2021,2021/03/22,PMC7961305,None,10.1016/j.jor.2021.03.001,==== Front\nJ Orthop\nJ Orthop\nJournal of Ort...
4,33815175,Prospective Long-Term Cohort Study of Subjects...,"Peralta V, Moreno-Izco L, García de Jalón E, S...",Front Psychiatry. 2021 Mar 19;12:643112. doi: ...,Peralta V,Front Psychiatry,2021,2021/04/05,PMC8017172,None,10.3389/fpsyt.2021.643112,==== Front\nFront Psychiatry\nFront Psychiatry...
...,...,...,...,...,...,...,...,...,...,...,...,...
5246,40476158,Artificial intelligence and chordoma: A scopin...,"Guo E, Sanguinetti RD, Boone L, Deng J, Shakil...",Brain Spine. 2025 May 3;5:104271. doi: 10.1016...,Guo E,Brain Spine,2025,2025/06/06,PMC12138559,None,10.1016/j.bas.2025.104271,==== Front\nBrain Spine\nBrain Spine\nBrain & ...
5247,39775871,AI as an intervention: improving clinical outc...,"Joshi S, Urteaga I, van Amsterdam WAC, Hripcsa...",J Am Med Inform Assoc. 2025 Mar 1;32(3):589-59...,Joshi S,J Am Med Inform Assoc,2025,2025/01/08,PMC11833492,None,10.1093/jamia/ocae301,==== Front\nJ Am Med Inform Assoc\nJ Am Med In...
5248,39885243,A comprehensive evaluation of histopathology f...,"Breen J, Allen K, Zucker K, Godson L, Orsi NM,...",NPJ Precis Oncol. 2025 Jan 30;9(1):33. doi: 10...,Breen J,NPJ Precis Oncol,2025,2025/01/30,PMC11782474,None,10.1038/s41698-025-00799-8,==== Front\nNPJ Precis Oncol\nNPJ Precis Oncol...
5249,39417095,An Ensemble Deep Learning Algorithm for Struct...,"Dhingra LS, Aminorroaya A, Sangha V, Pedroso A...",medRxiv [Preprint]. 2024 Dec 27:2024.10.06.243...,Dhingra LS,medRxiv,2024,2024/10/17,PMC11483021,None,10.1101/2024.10.06.24314939,==== Front\nmedRxiv\nMEDRXIV\nmedRxiv\nCold Sp...
5250,39529875,Detection of breast cancer using machine learn...,"Harnischmacher N, Rodner E, Schmitz CH.",J Biomed Opt. 2024 Nov;29(11):115001. doi: 10....,Harnischmacher N,J Biomed Opt,2024,2024/11/12,PMC11552526,None,10.1117/1.JBO.29.11.115001,==== Front\nJ Biomed Opt\nJ Biomed Opt\nJBOPFO...

In [4]:
dev.to_csv("../data/02_paper_assessment/gt_paper_assessment_dev.csv")
test.to_csv("../data/02_paper_assessment/gt_paper_assessment_test.csv")